create table spec_unit_manifest
(
	unit_manifest_id bigint generated by default as identity
		constraint unit_manifest_pkey
			primary key,
	production_orderline_id integer not null
		constraint unit_manifest_production_orderline_id_fkey
			references component_specs (production_orderline_id)
				on delete cascade,
	option_code text not null,
	param_json jsonb default '{}'::jsonb not null,
	item_code text,
	scope text not null,
	possible_status_sequence jsonb default '[]'::jsonb not null,
	config_json jsonb default '{}'::jsonb not null,
	production_impact_per_unit integer default 0 not null,
	price numeric(14,4) default 0 not null,
	sort_order integer default 0 not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table spec_unit_manifest owner to xfw3;

create index idx_unit_manifest_option_code
	on spec_unit_manifest (option_code);

create index idx_unit_manifest_item_code
	on spec_unit_manifest (item_code);

create index idx_unit_manifest_production_orderline_id
	on spec_unit_manifest (production_orderline_id);

