create table cart
(
	cart_id bigint generated by default as identity
		primary key,
	parent_cart_id bigint
		references cart
			on delete set null,
	type text not null,
	closed_at timestamp with time zone,
	cart_json jsonb default '{}'::jsonb not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table cart owner to xfw3;

create index idx_cart_parent_cart_id
	on cart (parent_cart_id);

create index idx_cart_open
	on cart (cart_id)
	where (closed_at IS NULL);

create index idx_cart_type
	on cart (type);

