create table line_item
(
	line_item_id bigint generated by default as identity
		primary key,
	cart_id bigint not null
		references cart
			on delete cascade,
	parent_line_item_id bigint
		references line_item
			on delete set null,
	option_tree_id bigint
		references catalog.option_tree,
	product_json jsonb default '{}'::jsonb not null,
	sales_price numeric(14,4),
	purchase_price numeric(14,4),
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table line_item owner to xfw3;

create index idx_line_item_cart_id
	on line_item (cart_id);

create index idx_line_item_parent_line_item_id
	on line_item (parent_line_item_id);

create index idx_line_item_product_json
	on line_item using gin (product_json jsonb_path_ops);

