create table spec_unit_manifest
(
	unit_manifest_id bigint generated by default as identity
		constraint unit_manifest_pkey
			primary key,
	spec_id bigint not null
		constraint unit_manifest_spec_id_fkey
			references spec
				on delete cascade,
	option_code text not null,
	param_json jsonb default '{}'::jsonb not null,
	item_code text not null,
	possible_status_sequence jsonb default '[]'::jsonb not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null,
	config_json jsonb default '{}'::jsonb not null,
	production_impact_per_unit integer default 0 not null,
	price numeric(14,4) default 0 not null
);

alter table spec_unit_manifest owner to xfw3;

create index idx_unit_manifest_spec_id
	on spec_unit_manifest (spec_id);

create index idx_unit_manifest_option_code
	on spec_unit_manifest (option_code);

create index idx_unit_manifest_item_code
	on spec_unit_manifest (item_code);

