create table spec
(
	spec_id bigint generated by default as identity
		primary key,
	line_item_id bigint not null
		references line_item
			on delete cascade,
	parent_spec_id bigint
		references spec
			on delete cascade,
	amount integer not null,
	spec_json jsonb default '{}'::jsonb not null,
	file_json jsonb default '[]'::jsonb not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null,
	closed_at timestamp with time zone
);

alter table spec owner to xfw3;

create index idx_spec_line_item_id
	on spec (line_item_id);

create index idx_spec_parent_spec_id
	on spec (parent_spec_id);

create index ix_spec_expiry
	on spec ((spec_json ->> 'expiry_date'::text))
	where (spec_json ? 'expiry_date'::text);

