create table batch
(
	batch_id bigint generated by default as identity,
	batch_sequence integer default 1 not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table batch owner to xfw3;

