create table imposition_unit_manifest
(
	imposition_unit_manifest_id bigint generated by default as identity
		primary key,
	imposition_id bigint not null
		references imposition
			on delete cascade,
	param_json jsonb default '{}'::jsonb not null,
	item_code text not null,
	possible_status_sequence jsonb default '[]'::jsonb not null,
	production_impact_per_unit integer default 0 not null,
	config_json jsonb default '{}'::jsonb not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table imposition_unit_manifest owner to xfw3;

create index idx_imposition_unit_manifest_imposition_id
	on imposition_unit_manifest (imposition_id);

create index idx_imposition_unit_manifest_item_code
	on imposition_unit_manifest (item_code);

