create table imposition
(
	imposition_id bigint generated by default as identity
		constraint nest_pkey
			primary key,
	batch_id bigint,
	width numeric not null,
	height numeric not null,
	amount integer not null
		constraint imposition_amount_check
			check (amount > 0),
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null,
	domain_id integer default 1 not null,
	waste_percentage numeric(3,1),
	placement_json jsonb
);

alter table imposition owner to xfw3;

create index idx_imposition_batch_id
	on imposition (batch_id);

