-- The tenant tree; a tenant without parent_tenant_id is a root (hoofd_tenant).
create table site.tenant
(
	tenant_id integer generated by default as identity
		primary key,
	parent_tenant_id integer
		references site.tenant (tenant_id),
	name text not null,
	abb text not null,
	production_company_id integer,
	created_at timestamp with time zone default now() not null
);

alter table site.tenant owner to xfw3;
