// Builds sql/update_data_group_inline.sql from json/data_group/xfw3_site_data_group.json:
// the same update as sql/update_data_group.sql, but with the json inline so it
// runs from SQLTools (no psql \set). Run from the repo root:
//   node scripts/build_update_data_group.js
const fs = require('fs');

const payload = fs.readFileSync('json/data_group/xfw3_site_data_group.json', 'utf8').replace(/\r?\n$/, '');
if (payload.includes('$dg$')) throw new Error('payload contains the dollar tag $dg$');

const sql = `-- GENERATED by scripts/build_update_data_group.js from json/data_group/xfw3_site_data_group.json
-- do not edit by hand, rebuild after every change to the json.
-- Plain sql version of update_data_group.sql, runs from SQLTools.
--

BEGIN;

-- One statement, the payload once: changed groups are updated in the CTE,
-- groups new to the table are inserted; the id comes from the export so json
-- and table stay in step. Unchanged rows are not touched.
WITH payload AS (
    SELECT $dg$${payload}$dg$::jsonb AS doc
),
src AS (
    SELECT (el ->> 'data_group_id')::integer AS data_group_id,
           el ->> 'data_group'               AS data_group,
           el -> 'data_group_json'           AS data_group_json
    FROM payload
             CROSS JOIN LATERAL jsonb_array_elements(payload.doc) AS el
),
updated AS (
    UPDATE site.data_group t
    SET data_group_json = s.data_group_json
    FROM src s
    WHERE t.data_group_id = s.data_group_id
      AND t.data_group_json IS DISTINCT FROM s.data_group_json
    RETURNING t.data_group_id
)
INSERT INTO site.data_group (data_group_id, data_group, data_group_json)
OVERRIDING SYSTEM VALUE
SELECT s.data_group_id, s.data_group, s.data_group_json
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM site.data_group t WHERE t.data_group_id = s.data_group_id);

-- data_group_id is an identity column; after inserting explicit ids the
-- sequence has to catch up, or the next generated id collides
SELECT setval(pg_get_serial_sequence('site.data_group', 'data_group_id'),
              (SELECT max(data_group_id) FROM site.data_group));

COMMIT;
`;

fs.writeFileSync('sql/update_data_group_inline.sql', sql);
console.log(`sql/update_data_group_inline.sql: ${sql.split('\n').length} lines`);
