create table item_group
(
	item_group_id bigint generated by default as identity
		primary key,
	item_group_code text not null
		unique,
	item_group_json jsonb not null,
	possible_status_sequence jsonb default '[]'::jsonb not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table item_group owner to xfw3;

