-- Versioned base price tiers per item (the root tenant price list).
-- Unit lives on catalog.item; tiers map amount -> price.
-- item_code_path is derived from item_code: SHEET-ACM-DIBOND-3MM -> sheet.acm.dibond.3mm
create table catalog.item_base_price
(
	item_base_price_id bigint generated by default as identity
		primary key,
	tenant_id integer,
	item_code text not null,
	item_code_path ltree generated always as (text2ltree(replace(lower(item_code), '-', '.'))) stored,
	price_tiers_json jsonb default '[{"from_amount": 1, "price": 0}]'::jsonb not null,
	version integer default 1 not null,
	version_status text default 'active'::text not null,
	created_at timestamp with time zone default now() not null
);

alter table catalog.item_base_price owner to xfw3;

create index idx_catalog_item_base_price_path
	on catalog.item_base_price using gist (item_code_path);
