-- Per tenant the price rule relative to its parent tenant, scoped by
-- item_code_path ('' = the whole price list, sheet.acm = that subtree).
-- Consolidation happens at read time (catalog.get_item_prices).
create table catalog.item_price_formula
(
	item_price_formula_id bigint generated by default as identity
		primary key,
	tenant_id integer not null,
	item_code_path ltree default ''::ltree not null,
	formula_json jsonb not null,
	version integer default 1 not null,
	version_status text default 'active'::text not null,
	created_at timestamp with time zone default now() not null
);

alter table catalog.item_price_formula owner to xfw3;

create index idx_catalog_item_price_formula_path
	on catalog.item_price_formula using gist (item_code_path);
