create table item
(
	item_id bigint generated by default as identity
		primary key,
	item_code text not null
		unique,
	item_code_path ltree generated always as (text2ltree(replace(lower(item_code), '-', '.'))) stored,
	item_group_code text not null
		references item_group (item_group_code),
	description text not null,
	item_json jsonb not null,
	created_at timestamp with time zone default now() not null,
	version integer default 1 not null,
	version_status text default 'active'::text not null
);

alter table item owner to xfw3;

create index idx_item_item_group_code
	on item (item_group_code);

create index idx_item_code_path_gist
	on item using gist (item_code_path);

