create table option_tree
(
	option_tree_id bigint generated by default as identity
		primary key,
	option_tree text not null,
	option_tree_json jsonb not null,
	created_at timestamp with time zone default now() not null,
	updated_at timestamp with time zone default now() not null
);

alter table option_tree owner to xfw3;

