create table catalog.option_tree
(
	option_tree_id bigint generated by default as identity
		primary key,
	tenant_id integer,
	company_id integer,
	option_tree text not null,
	option_tree_json jsonb not null,
	file_json jsonb,
	version integer default 1 not null,
	version_status text default 'active'::text not null,
	created_at timestamp with time zone default now() not null
);

alter table catalog.option_tree owner to xfw3;
