-- ============================================================
-- Migration: catalog.imposition_group — planning moves from
-- material to imposition group.
--
-- Run BEFORE sql/migration_lane_slots.sql: the slot link table
-- (action.imposition_group_lane_item) references this one.
--
-- The seed derives one group per material from
-- mapping.material_production_line, with imposition_group_id =
-- material_id (the ids stay interchangeable during the
-- transition) and item_code_paths[1] built from the line_json:
-- material_media_type (roll/sheet/piece; missing = roll, those
-- are the textile rows) + material_name as a path. Eleven
-- materials share a name; their path gets the material_id as an
-- extra label — refine by hand afterwards.
-- ============================================================

BEGIN;

CREATE TABLE catalog.imposition_group
(
    imposition_group_id integer GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    item_code_paths ltree[] NOT NULL
        CONSTRAINT imposition_group_item_code_paths_key
            UNIQUE
);

ALTER TABLE catalog.imposition_group OWNER TO xfw3;

CREATE INDEX idx_catalog_imposition_group_paths_gist
    ON catalog.imposition_group USING gist (item_code_paths);

-- seed: one group per material, id = material_id
WITH src AS (
    SELECT DISTINCT ON (material_id)
           material_id,
           coalesce(line_json ->> 'material_media_type', 'roll') AS media_type,
           line_json ->> 'material_name'                         AS material_name
    FROM mapping.material_production_line
    WHERE line_json ->> 'material_name' IS NOT NULL
    ORDER BY material_id, (line_json ->> 'material_media_type') NULLS LAST
),
pathed AS (
    SELECT material_id,
           text2ltree(media_type || '.' ||
               trim(both '.' from regexp_replace(lower(material_name), '[^a-z0-9]+', '.', 'g'))) AS path
    FROM src
),
deduped AS (
    -- materials sharing a name get their id as an extra label
    SELECT material_id,
           CASE WHEN count(*) OVER (PARTITION BY path) > 1
                THEN path || material_id::text
                ELSE path END AS path
    FROM pathed
)
INSERT INTO catalog.imposition_group (imposition_group_id, item_code_paths)
SELECT material_id, ARRAY[path]
FROM deduped
ORDER BY material_id;

SELECT setval(pg_get_serial_sequence('catalog.imposition_group', 'imposition_group_id'),
              (SELECT max(imposition_group_id) FROM catalog.imposition_group), true);

COMMIT;

-- >>> then run:
--     sql/catalog/get_imposition_group.sql   (find-or-create from the xbom)
--     sql/migration_lane_slots.sql           (slots + the group link per slot)
--     sql/mock/generate_plan.sql             (stamps the group link on new plans)
