-- GENERATED by scripts/build_update_data_group.js from json/data_group/xfw3_site_data_group.json
-- do not edit by hand, rebuild after every change to the json.
-- Plain sql version of update_data_group.sql, runs from SQLTools.
-- ONLY data groups 62 resource_oee_area_chart
--

BEGIN;

-- One statement, the payload once: changed groups are updated in the CTE,
-- groups new to the table are inserted; the id comes from the export so json
-- and table stay in step. Unchanged rows are not touched.
WITH payload AS (
    SELECT $dg$[
  {
    "data_group_id": 62,
    "data_group": "resource_oee_area_chart",
    "data_group_json": [
      {
        "src": [
          "get_resource_state_shift_totals"
        ],
        "layout": "flow-board",
        "params": [
          {
            "key": "resource_uids",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "until",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "days",
            "is_optional": true,
            "default_value": 42
          },
          {
            "key": "line_type",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "states",
            "is_optional": true,
            "default_value": [
              "producing",
              "setup",
              "breakdown",
              "maintenance",
              "interruption",
              "offline",
              "installation",
              "missingdata"
            ],
            "is_query_param": true
          },
          {
            "key": "include_weekends",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "include_mandatory_days_off",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "include_shifts",
            "is_optional": true,
            "is_query_param": true
          }
        ],
        "widget_id": "resource_state_shift_percent",
        "field_config": {
          "step": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Schritt"
                },
                "en": {
                  "title": "Step"
                },
                "es": {
                  "title": "Paso"
                },
                "fr": {
                  "title": "Étape"
                },
                "nl": {
                  "title": "Stap"
                },
                "uk": {
                  "title": "Крок"
                }
              },
              "order": 3,
              "no_label": true
            }
          },
          "state": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "State"
                },
                "es": {
                  "title": "Estado"
                },
                "fr": {
                  "title": "État"
                },
                "nl": {
                  "title": "Status"
                },
                "uk": {
                  "title": "Стан"
                }
              },
              "order": 4
            }
          },
          "shift_date": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Datum"
                },
                "en": {
                  "title": "Date"
                },
                "es": {
                  "title": "Fecha"
                },
                "fr": {
                  "title": "Date"
                },
                "nl": {
                  "title": "Datum"
                },
                "uk": {
                  "title": "Дата"
                }
              },
              "type": "date",
              "order": 0
            }
          },
          "sort_order": {
            "ui": {
              "order": 4,
              "hidden": true
            }
          },
          "state_json": {
            "ui": {
              "hidden": true
            }
          },
          "shift_index": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Schicht"
                },
                "en": {
                  "title": "Shift"
                },
                "es": {
                  "title": "Turno"
                },
                "fr": {
                  "title": "Équipe"
                },
                "nl": {
                  "title": "Shift"
                },
                "uk": {
                  "title": "Зміна"
                }
              },
              "order": 1
            }
          },
          "resource_uid": {
            "ui": {
              "hidden": true
            }
          },
          "resource_name": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Maschine"
                },
                "en": {
                  "title": "Resource"
                },
                "es": {
                  "title": "Máquina"
                },
                "fr": {
                  "title": "Machine"
                },
                "nl": {
                  "title": "Machine"
                },
                "uk": {
                  "title": "Машина"
                }
              },
              "order": 2
            }
          },
          "duration_seconds": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Dauer"
                },
                "en": {
                  "title": "Duration"
                },
                "es": {
                  "title": "Duración"
                },
                "fr": {
                  "title": "Durée"
                },
                "nl": {
                  "title": "Duur"
                },
                "uk": {
                  "title": "Тривалість"
                }
              },
              "type": "duration",
              "order": 5
            }
          },
          "oee_json.producing_oee": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "OEE"
                },
                "en": {
                  "title": "OEE"
                },
                "es": {
                  "title": "OEE"
                },
                "fr": {
                  "title": "OEE"
                },
                "nl": {
                  "title": "OEE"
                },
                "uk": {
                  "title": "OEE"
                }
              }
            }
          },
          "param_json.total_shift_hours": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Schichtstunden"
                },
                "en": {
                  "title": "Shift hours"
                },
                "es": {
                  "title": "Shift hours"
                },
                "fr": {
                  "title": "Shift hours"
                },
                "nl": {
                  "title": "Shifturen"
                },
                "uk": {
                  "title": "Shift hours"
                }
              }
            }
          }
        },
        "flow_board_config": {
          "layout": "flow-grid",
          "children": [
            {
              "layout": "stacked-area-chart",
              "stacked_area_chart_config": {
                "height": 420,
                "stacked": true,
                "tooltip": {
                  "header": {
                    "group": {
                      "fields_class_name": "grid grid-cols-6 gap-1",
                      "field_config": {
                        "shift_date": {
                          "ui": {
                            "order": 0,
                            "class_name": "col-span-4"
                          }
                        },
                        "step": {
                          "ui": {
                            "order": 1,
                            "class_name": "col-span-2 text-right"
                          }
                        },
                        "param_json.total_shift_hours": {
                          "ui": {
                            "order": 2,
                            "class_name": "col-span-3"
                          }
                        },
                        "oee_json.producing_oee": {
                          "ui": {
                            "order": 3,
                            "class_name": "col-span-3 text-right"
                          },
                          "type": "percent"
                        }
                      }
                    }
                  },
                  "sections": [
                    {
                      "group": {
                        "fields_class_name": "grid grid-cols-9 gap-1",
                        "field_config": {
                          "state": {
                            "ui": {
                              "order": 0,
                              "class_name": "col-span-5"
                            }
                          },
                          "duration_seconds": {
                            "ui": {
                              "order": 1,
                              "class_name": "col-span-4 text-right"
                            },
                            "type": "duration",
                            "format": "hh:mm"
                          }
                        }
                      }
                    }
                  ]
                },
                "x_field": "shift_date",
                "y_field": "duration_seconds",
                "set_field": "counts_as",
                "show_grid": true,
                "normalized": false,
                "show_legend": true,
                "set_overrides": {
                  "planned": {
                    "type": "line",
                    "stacked": false
                  },
                  "available": {
                    "no_legend": true,
                    "no_tooltip": true
                  }
                },
                "set_order_field": "sort_order",
                "optional_group_fields": [
                  "shift_index"
                ],
                "group_by": [
                  "line",
                  "step",
                  "resource_uid"
                ],
                "class_names_field": "state_json.class_name",
                "y_axis": {
                  "format": "hh:mm",
                  "begin_at_zero": true,
                  "max_field": "param_json.total_shift_in_seconds"
                },
                "fill_field": "state_json.fill",
                "color_field": "state_json.color"
              }
            }
          ],
          "group_by": [
            "shift_index"
          ],
          "row_options": {
            "colexp": false,
            "checkable": false,
            "selectable": false
          }
        },
        "window_class_name": "p-8",
        "fields_class_name": "grid grid-cols-6 gap-1"
      }
    ]
  }
]$dg$::jsonb AS doc
),
src AS (
    SELECT (el ->> 'data_group_id')::integer AS data_group_id,
           el ->> 'data_group'               AS data_group,
           el -> 'data_group_json'           AS data_group_json
    FROM payload
             CROSS JOIN LATERAL jsonb_array_elements(payload.doc) AS el
),
updated AS (
    UPDATE site.data_group t
    SET data_group      = s.data_group,
        data_group_json = s.data_group_json
    FROM src s
    WHERE t.data_group_id = s.data_group_id
      AND (t.data_group_json IS DISTINCT FROM s.data_group_json
           OR t.data_group IS DISTINCT FROM s.data_group)
    RETURNING t.data_group_id
)
INSERT INTO site.data_group (data_group_id, data_group, data_group_json)
OVERRIDING SYSTEM VALUE
SELECT s.data_group_id, s.data_group, s.data_group_json
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM site.data_group t WHERE t.data_group_id = s.data_group_id);

-- data_group_id is an identity column; after inserting explicit ids the
-- sequence has to catch up, or the next generated id collides
SELECT setval(pg_get_serial_sequence('site.data_group', 'data_group_id'),
              (SELECT max(data_group_id) FROM site.data_group));

COMMIT;
