-- GENERATED by scripts/build_update_data_group.js from json/data_group/xfw3_site_data_group.json
-- do not edit by hand, rebuild after every change to the json.
-- Plain sql version of update_data_group.sql, runs from SQLTools.
-- ONLY data groups 48 production_board, 49 production_board_detail, 79 nest_schedule_queue
--

BEGIN;

-- One statement, the payload once: changed groups are updated in the CTE,
-- groups new to the table are inserted; the id comes from the export so json
-- and table stay in step. Unchanged rows are not touched.
WITH payload AS (
    SELECT $dg$[
  {
    "data_group_id": 48,
    "data_group": "production_board",
    "data_group_json": [
      {
        "src": [
          "get_production_board_aggregate"
        ],
        "layout": "flow-board",
        "params": [
          {
            "key": "from",
            "is_query_param": true
          },
          {
            "key": "look_back_days",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "look_ahead_days",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "production_line_id",
            "is_query_param": true
          },
          {
            "key": "status_levels",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "nest_ids",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "domain_id",
            "default_value": 1
          }
        ],
        "children": [],
        "widget_id": "production_board",
        "field_config": {
          "nest_ids": {
            "ui": {
              "hidden": true
            }
          },
          "rework_sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "H. m²"
                },
                "en": {
                  "title": "Rw m²"
                },
                "nl": {
                  "title": "H. m²"
                }
              },
              "order": 8,
              "scale": 1
            }
          },
          "material_id": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Material-ID"
                },
                "en": {
                  "title": "Material ID"
                },
                "nl": {
                  "title": "Materiaal-ID"
                }
              },
              "order": 10,
              "hidden": true
            }
          },
          "order_count": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Aufträge"
                },
                "en": {
                  "title": "Orders"
                },
                "nl": {
                  "title": "Orders"
                }
              },
              "order": 3
            }
          },
          "regular_sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "m²"
                },
                "en": {
                  "title": "m²"
                },
                "nl": {
                  "title": "m²"
                }
              },
              "order": 5,
              "scale": 1
            }
          },
          "material_sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "m²"
                },
                "en": {
                  "title": "m²"
                },
                "nl": {
                  "title": "m²"
                }
              },
              "order": 14,
              "scale": 1
            }
          },
          "rework_count": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Nacharbeit"
                },
                "en": {
                  "title": "Rework"
                },
                "nl": {
                  "title": "Herstel"
                }
              },
              "order": 6
            }
          },
          "status_title": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "Status"
                },
                "nl": {
                  "title": "Status"
                }
              },
              "order": 1
            }
          },
          "material_name": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Material"
                },
                "en": {
                  "title": "Material"
                },
                "nl": {
                  "title": "Materiaal"
                }
              },
              "order": 11
            }
          },
          "rework_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "H. Einheiten"
                },
                "en": {
                  "title": "Rw units"
                },
                "nl": {
                  "title": "H. units"
                }
              },
              "order": 7
            }
          },
          "logistics_date": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Datum"
                },
                "en": {
                  "title": "Date"
                },
                "nl": {
                  "title": "Datum"
                }
              },
              "order": 2,
              "type": "date"
            }
          },
          "regular_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Einheiten"
                },
                "en": {
                  "title": "Units"
                },
                "nl": {
                  "title": "Units"
                }
              },
              "order": 4
            }
          },
          "distribution_json": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "Status"
                },
                "es": {
                  "title": "Estado"
                },
                "fr": {
                  "title": "Statut"
                },
                "nl": {
                  "title": "Status"
                },
                "uk": {
                  "title": "Статус"
                }
              },
              "order": 9,
              "control": "distribution-bar",
              "distribution_bar_config": {
                "i18n_field": "i18n",
                "value_field": "amount",
                "class_names_field": "class_names",
                "sort": {
                  "field": "sequence"
                }
              }
            }
          },
          "material_rework_sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "H. m²"
                },
                "en": {
                  "title": "Rw m²"
                },
                "nl": {
                  "title": "H. m²"
                }
              },
              "order": 17,
              "scale": 1
            }
          },
          "delivery_class_names": {
            "ui": {
              "hidden": true
            }
          },
          "internal_status_code": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "Status"
                },
                "nl": {
                  "title": "Status"
                }
              },
              "order": 0,
              "control": "badge",
              "no_label": true
            }
          },
          "material_order_count": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Aufträge"
                },
                "en": {
                  "title": "Orders"
                },
                "nl": {
                  "title": "Orders"
                }
              },
              "order": 12
            }
          },
          "day_distribution_json": {
            "ui": {
              "hidden": false
            }
          },
          "material_rework_count": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Nacharbeit"
                },
                "en": {
                  "title": "Rework"
                },
                "nl": {
                  "title": "Herstel"
                }
              },
              "order": 15
            }
          },
          "material_rework_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "H. Einheiten"
                },
                "en": {
                  "title": "Rw units"
                },
                "nl": {
                  "title": "H. units"
                }
              },
              "order": 16
            }
          },
          "material_product_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Einheiten"
                },
                "en": {
                  "title": "Units"
                },
                "nl": {
                  "title": "Units"
                }
              },
              "order": 13
            }
          },
          "material_distribution_json": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "Status"
                },
                "es": {
                  "title": "Estado"
                },
                "fr": {
                  "title": "Statut"
                },
                "nl": {
                  "title": "Status"
                },
                "uk": {
                  "title": "Статус"
                }
              },
              "order": 18,
              "control": "distribution-bar",
              "distribution_bar_config": {
                "i18n_field": "i18n",
                "value_field": "amount",
                "class_names_field": "class_names",
                "sort": {
                  "field": "sequence"
                }
              }
            }
          }
        },
        "flow_board_config": {
          "layout": "flow-grid",
          "children": [
            {
              "layout": "flow-container",
              "children": [
                {
                  "layout": "flow-cards",
                  "children": [
                    {
                      "layout": "flow-cards",
                      "row_options": {
                        "nav": {
                          "menu": [
                            {
                              "i18n": {
                                "de": {
                                  "title": "Aufträge"
                                },
                                "en": {
                                  "title": "Orders"
                                },
                                "es": {
                                  "title": "Pedidos"
                                },
                                "fr": {
                                  "title": "Commandes"
                                },
                                "nl": {
                                  "title": "Orders"
                                },
                                "uk": {
                                  "title": "Замовлення"
                                }
                              },
                              "path": "(sidebar:production-board-detail)",
                              "params": [
                                {
                                  "key": "from",
                                  "value_from": "logistics_date",
                                  "is_query_param": true
                                },
                                {
                                  "key": "look_back_days",
                                  "default_value": 0
                                },
                                {
                                  "key": "look_ahead_days",
                                  "default_value": 0
                                },
                                {
                                  "key": "production_line_id",
                                  "is_query_param": true
                                },
                                {
                                  "key": "material_ids",
                                  "is_query_param": true,
                                  "value_from": "material_id"
                                },
                                {
                                  "key": "logistics_at",
                                  "is_query_param": true,
                                  "value_from": "logistics_datetime"
                                },
                                {
                                  "key": "status_sequences",
                                  "value_from": "status_sequence",
                                  "is_query_param": true
                                }
                              ]
                            },
                            {
                              "i18n": {
                                "de": {
                                  "title": "Nest detail"
                                },
                                "en": {
                                  "title": "Nest detail"
                                },
                                "es": {
                                  "title": "Detalle del nido"
                                },
                                "fr": {
                                  "title": "Détail du nid"
                                },
                                "nl": {
                                  "title": "Nest detail"
                                },
                                "uk": {
                                  "title": "Деталі гнізда"
                                }
                              },
                              "path": "(sidebar:nest-detail)",
                              "params": [
                                {
                                  "key": "nest_ids",
                                  "is_query_param": true
                                }
                              ],
                              "hidden_when": [
                                {
                                  "op": "<=",
                                  "value": 450,
                                  "field": "status_sequence"
                                }
                              ]
                            }
                          ],
                          "on_select": {
                            "params": [
                              {
                                "key": "material_ids",
                                "value_from": "material_id",
                                "is_query_param": true
                              },
                              {
                                "key": "logistics_at",
                                "value_from": "logistics_datetime",
                                "is_query_param": true
                              },
                              {
                                "key": "status_sequences",
                                "value_from": "status_sequence",
                                "is_query_param": true
                              }
                            ]
                          }
                        },
                        "colexp": false,
                        "checkable": false,
                        "selectable": true,
                        "deselectable": true
                      },
                      "field_config": {
                        "material_sqm": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "m²"
                              },
                              "en": {
                                "title": "m²"
                              },
                              "nl": {
                                "title": "m²"
                              }
                            },
                            "order": 3,
                            "scale": 1,
                            "class_name": "col-span-2"
                          }
                        },
                        "material_name": {
                          "ui": {
                            "order": 0,
                            "class_name": "col-span-6 font-medium"
                          }
                        },
                        "material_rework_sqm": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "H. m²"
                              },
                              "en": {
                                "title": "Rw m²"
                              },
                              "nl": {
                                "title": "H. m²"
                              }
                            },
                            "order": 6,
                            "scale": 1,
                            "class_name": "col-span-2",
                            "hidden_when": [
                              {
                                "op": "==",
                                "value": 0,
                                "field": "material_rework_count"
                              }
                            ]
                          }
                        },
                        "material_order_count": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Aufträge"
                              },
                              "en": {
                                "title": "Orders"
                              },
                              "nl": {
                                "title": "Orders"
                              }
                            },
                            "order": 1,
                            "class_name": "col-span-2"
                          }
                        },
                        "material_rework_count": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Nacharbeit"
                              },
                              "en": {
                                "title": "Rework"
                              },
                              "nl": {
                                "title": "Herstel"
                              }
                            },
                            "order": 4,
                            "class_name": "col-span-2",
                            "hidden_when": [
                              {
                                "op": "==",
                                "value": 0,
                                "field": "material_rework_count"
                              }
                            ]
                          }
                        },
                        "material_rework_amount": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "H. Einheiten"
                              },
                              "en": {
                                "title": "Rw units"
                              },
                              "nl": {
                                "title": "H. units"
                              }
                            },
                            "order": 5,
                            "class_name": "col-span-2",
                            "hidden_when": [
                              {
                                "op": "==",
                                "value": 0,
                                "field": "material_rework_count"
                              }
                            ]
                          }
                        },
                        "material_product_amount": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Einheiten"
                              },
                              "en": {
                                "title": "Units"
                              },
                              "nl": {
                                "title": "Units"
                              }
                            },
                            "order": 2,
                            "class_name": "col-span-2"
                          }
                        },
                        "material_distribution_json": {
                          "ui": {
                            "order": 7,
                            "control": "distribution-bar",
                            "class_name": "col-span-6",
                            "distribution_bar_config": {
                              "i18n_field": "i18n",
                              "value_field": "amount",
                              "class_names_field": "class_names",
                              "sort": {
                                "field": "sequence"
                              }
                            }
                          }
                        }
                      },
                      "filter_match": "all",
                      "filter_fields": [
                        "internal_status_code",
                        "material_id",
                        "nest_ids",
                        "logistics_date",
                        "logistics_datetime"
                      ],
                      "fields_class_name": "grid grid-cols-6 gap-1"
                    }
                  ],
                  "group_by": [
                    "logistics_datetime"
                  ],
                  "hidden_when": [
                    {
                      "op": "==",
                      "value": false,
                      "field": "is_logistics_date_today"
                    }
                  ],
                  "row_options": {
                    "colexp": true,
                    "checkable": false,
                    "selectable": false,
                    "colexp_field": "${logistics_datetime}",
                    "class_names_field": "delivery_class_names"
                  },
                  "field_config": {
                    "material_sqm": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "m²"
                          },
                          "en": {
                            "title": "m²"
                          },
                          "nl": {
                            "title": "m²"
                          }
                        },
                        "order": 4,
                        "scale": 1,
                        "class_name": "col-span-2"
                      },
                      "aggregate_fn": "sum"
                    },
                    "distribution_json": {
                      "ui": {
                        "order": 1,
                        "control": "distribution-bar",
                        "class_name": "col-span-6",
                        "distribution_bar_config": {
                          "i18n_field": "i18n",
                          "value_field": "amount",
                          "class_names_field": "class_names",
                          "sort": {
                            "field": "sequence"
                          }
                        }
                      }
                    },
                    "logistics_datetime": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Zeit"
                          },
                          "en": {
                            "title": "Time"
                          },
                          "nl": {
                            "title": "Tijd"
                          }
                        },
                        "type": "datetime",
                        "order": 0,
                        "class_name": "col-span-6"
                      }
                    },
                    "material_rework_sqm": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "H. m²"
                          },
                          "en": {
                            "title": "Rw m²"
                          },
                          "nl": {
                            "title": "H. m²"
                          }
                        },
                        "order": 8,
                        "scale": 1,
                        "class_name": "col-span-2",
                        "hidden_when": [
                          {
                            "op": "==",
                            "value": 0,
                            "field": "material_rework_count"
                          }
                        ]
                      },
                      "aggregate_fn": "sum"
                    },
                    "material_order_count": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Aufträge"
                          },
                          "en": {
                            "title": "Orders"
                          },
                          "nl": {
                            "title": "Orders"
                          }
                        },
                        "order": 3,
                        "class_name": "col-span-2"
                      },
                      "aggregate_fn": "sum"
                    },
                    "material_rework_count": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Nacharbeit"
                          },
                          "en": {
                            "title": "Rework"
                          },
                          "nl": {
                            "title": "Herstel"
                          }
                        },
                        "order": 6,
                        "class_name": "col-span-2",
                        "hidden_when": [
                          {
                            "op": "==",
                            "value": 0,
                            "field": "material_rework_count"
                          }
                        ]
                      },
                      "aggregate_fn": "sum"
                    },
                    "material_rework_amount": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "H. Einheiten"
                          },
                          "en": {
                            "title": "Rw units"
                          },
                          "nl": {
                            "title": "H. units"
                          }
                        },
                        "order": 7,
                        "class_name": "col-span-2",
                        "hidden_when": [
                          {
                            "op": "==",
                            "value": 0,
                            "field": "material_rework_count"
                          }
                        ]
                      },
                      "aggregate_fn": "sum"
                    },
                    "material_product_amount": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Einheiten"
                          },
                          "en": {
                            "title": "Units"
                          },
                          "nl": {
                            "title": "Units"
                          }
                        },
                        "order": 5,
                        "class_name": "col-span-2"
                      },
                      "aggregate_fn": "sum"
                    }
                  },
                  "fields_class_name": "grid grid-cols-6 gap-1"
                }
              ],
              "group_by": [
                "logistics_date",
                "internal_status_code"
              ],
              "row_options": {
                "colexp": true,
                "checkable": false,
                "selectable": false,
                "class_names_field": "delivery_class_names"
              },
              "field_config": {
                "material_sqm": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "m²"
                      },
                      "en": {
                        "title": "m²"
                      },
                      "nl": {
                        "title": "m²"
                      }
                    },
                    "order": 4,
                    "scale": 1,
                    "class_name": "col-span-2"
                  },
                  "aggregate_fn": "sum"
                },
                "logistics_date": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Datum"
                      },
                      "en": {
                        "title": "Date"
                      },
                      "nl": {
                        "title": "Datum"
                      }
                    },
                    "type": "date",
                    "order": 0,
                    "class_name": "col-span-3"
                  }
                },
                "material_rework_sqm": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "H. m²"
                      },
                      "en": {
                        "title": "Rw m²"
                      },
                      "nl": {
                        "title": "H. m²"
                      }
                    },
                    "order": 7,
                    "scale": 1,
                    "class_name": "col-span-2",
                    "hidden_when": [
                      {
                        "op": "==",
                        "value": 0,
                        "field": "material_rework_count"
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                },
                "material_order_count": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Aufträge"
                      },
                      "en": {
                        "title": "Orders"
                      },
                      "nl": {
                        "title": "Orders"
                      }
                    },
                    "order": 2,
                    "class_name": "col-span-2"
                  },
                  "aggregate_fn": "sum"
                },
                "day_distribution_json": {
                  "ui": {
                    "order": 1,
                    "control": "distribution-bar",
                    "class_name": "col-span-3",
                    "distribution_bar_config": {
                      "i18n_field": "i18n",
                      "value_field": "amount",
                      "class_names_field": "class_names",
                      "sort": {
                        "field": "sequence"
                      }
                    }
                  }
                },
                "material_rework_count": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Nacharbeit"
                      },
                      "en": {
                        "title": "Rework"
                      },
                      "nl": {
                        "title": "Herstel"
                      }
                    },
                    "order": 5,
                    "class_name": "col-span-2",
                    "hidden_when": [
                      {
                        "op": "==",
                        "value": 0,
                        "field": "material_rework_count"
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                },
                "material_rework_amount": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "H. Einheiten"
                      },
                      "en": {
                        "title": "Rw units"
                      },
                      "nl": {
                        "title": "H. units"
                      }
                    },
                    "order": 6,
                    "class_name": "col-span-2",
                    "hidden_when": [
                      {
                        "op": "==",
                        "value": 0,
                        "field": "material_rework_count"
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                },
                "material_product_amount": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Einheiten"
                      },
                      "en": {
                        "title": "Units"
                      },
                      "nl": {
                        "title": "Units"
                      }
                    },
                    "order": 3,
                    "class_name": "col-span-2"
                  },
                  "aggregate_fn": "sum"
                }
              },
              "fields_class_name": "grid grid-cols-6 gap-1"
            }
          ],
          "group_by": [
            "internal_status_code"
          ],
          "row_options": {
            "colexp": false,
            "checkable": false,
            "selectable": true,
            "deselectable": true
          },
          "field_config": {
            "status_title": {
              "ui": {
                "no_label": true,
                "class_name": "col-span-1"
              }
            },
            "internal_status_code": {
              "ui": {
                "hidden": true
              }
            }
          },
          "column_max_width": 300,
          "column_min_width": 300,
          "fields_class_name": "grid grid-cols-1",
          "hidden_when_column_empty": true
        }
      }
    ]
  },
  {
    "data_group_id": 49,
    "data_group": "production_board_detail",
    "data_group_json": [
      {
        "src": [
          "get_production_orderline_detail"
        ],
        "layout": "flow-board",
        "params": [
          {
            "key": "production_line_id",
            "is_query_param": true
          },
          {
            "key": "status_sequences",
            "is_query_param": true,
            "is_optional": true
          },
          {
            "key": "from",
            "is_query_param": true
          },
          {
            "key": "look_back_days",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "look_ahead_days",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "material_ids",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "domain_id",
            "default_value": 1
          },
          {
            "key": "logistics_at",
            "is_optional": true,
            "is_query_param": true
          }
        ],
        "children": [],
        "widget_id": "production_board_detail",
        "field_config": {
          "sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "m²"
                },
                "en": {
                  "title": "m²"
                },
                "nl": {
                  "title": "m²"
                }
              },
              "order": 5
            },
            "scale": 1
          },
          "number": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Auftrag"
                },
                "en": {
                  "title": "Order"
                },
                "nl": {
                  "title": "Order"
                }
              },
              "order": 1
            }
          },
          "nest_ids": {
            "ui": {
              "hidden": true
            }
          },
          "team_name": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Team"
                },
                "en": {
                  "title": "Team"
                },
                "nl": {
                  "title": "Team"
                }
              },
              "order": 13
            }
          },
          "impact_json": {
            "ui": {
              "hidden": true
            }
          },
          "material_id": {
            "ui": {
              "hidden": true
            }
          },
          "nest_counts": {
            "ui": {
              "hidden": true
            }
          },
          "part_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Teile"
                },
                "en": {
                  "title": "Parts"
                },
                "nl": {
                  "title": "Delen"
                }
              },
              "order": 10
            }
          },
          "rework_count": {
            "ui": {
              "hidden": true
            }
          },
          "status_title": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "Status"
                },
                "nl": {
                  "title": "Status"
                }
              },
              "order": 9
            }
          },
          "manifest_json": {
            "ui": {
              "hidden": true
            }
          },
          "material_name": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Material"
                },
                "en": {
                  "title": "Material"
                },
                "nl": {
                  "title": "Materiaal"
                }
              },
              "order": 0
            }
          },
          "rework_amount": {
            "ui": {
              "hidden": true
            }
          },
          "logistics_date": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Logistikdatum"
                },
                "en": {
                  "title": "Logistics date"
                },
                "nl": {
                  "title": "Logistiek datum"
                }
              },
              "order": 6,
              "type": "date"
            }
          },
          "product_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Menge"
                },
                "en": {
                  "title": "Qty"
                },
                "nl": {
                  "title": "Aantal"
                }
              },
              "order": 4
            },
            "scale": 0
          },
          "produced_amount": {
            "ui": {
              "hidden": true
            }
          },
          "production_date": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Produktionsdatum"
                },
                "en": {
                  "title": "Production date"
                },
                "nl": {
                  "title": "Productiedatum"
                }
              },
              "order": 8,
              "type": "date"
            }
          },
          "rejected_amount": {
            "ui": {
              "hidden": true
            }
          },
          "status_sequence": {
            "ui": {
              "hidden": true
            }
          },
          "part_status_json": {
            "ui": {
              "hidden": true
            }
          },
          "nest_rework_count": {
            "ui": {
              "hidden": true
            }
          },
          "part_status_count": {
            "ui": {
              "hidden": true
            }
          },
          "status_class_name": {
            "ui": {
              "hidden": true
            }
          },
          "logistics_datetime": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Logistikzeit"
                },
                "en": {
                  "title": "Logistics time"
                },
                "nl": {
                  "title": "Logistiek tijdstip"
                }
              },
              "order": 7,
              "type": "datetime"
            }
          },
          "nest_rework_amount": {
            "ui": {
              "hidden": true
            }
          },
          "sales_orderline_id": {
            "ui": {
              "hidden": true
            }
          },
          "production_order_id": {
            "ui": {
              "hidden": true
            }
          },
          "internal_status_code": {
            "ui": {
              "hidden": true
            }
          },
          "is_logistics_date_today": {
            "ui": {
              "hidden": true
            }
          },
          "production_orderline_id": {
            "ui": {
              "hidden": true
            }
          },
          "orderline_status_sequence": {
            "ui": {
              "hidden": true
            }
          },
          "duration_in_seconds_to_logistics_date": {
            "ui": {
              "hidden": true
            }
          },
          "duration_in_seconds_to_production_date": {
            "ui": {
              "hidden": true
            }
          },
          "customer_json.company_name": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Kunde"
                },
                "en": {
                  "title": "Customer"
                },
                "nl": {
                  "title": "Klant"
                }
              },
              "order": 2
            }
          },
          "customer_json.customer_reference": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Referenz"
                },
                "en": {
                  "title": "Reference"
                },
                "nl": {
                  "title": "Referentie"
                }
              },
              "order": 12
            }
          }
        },
        "flow_board_config": {
          "layout": "flow-container",
          "search": [
            "number",
            "customer_json.company_name",
            "material_name",
            "status_title"
          ],
          "group_by": [
            "material_id",
            "material_name"
          ],
          "row_options": {
            "colexp": true,
            "checkable": false,
            "selectable": false
          },
          "field_config": {
            "material_name": {
              "ui": {
                "order": 0,
                "class_name": "col-span-3"
              }
            }
          },
          "fields_class_name": "grid grid-cols-3 gap-1",
          "children": [
            {
              "layout": "flow-container",
              "group_by": [
                "manifest_json.imposition"
              ],
              "row_options": {
                "colexp": true,
                "checkable": false,
                "selectable": false
              },
              "field_config": {
                "manifest_json.imposition.i18n": {
                  "ui": {
                    "order": 0,
                    "class_name": "col-span-3"
                  }
                },
                "order_count": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Aufträge"
                      },
                      "en": {
                        "title": "Orders"
                      },
                      "nl": {
                        "title": "Orders"
                      }
                    },
                    "order": 1,
                    "class_name": "col-span-1"
                  },
                  "aggregate_fn": "sum"
                },
                "product_amount": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Einheiten"
                      },
                      "en": {
                        "title": "Units"
                      },
                      "nl": {
                        "title": "Units"
                      }
                    },
                    "order": 2,
                    "class_name": "col-span-1"
                  },
                  "aggregate_fn": "sum"
                },
                "sqm": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "m²"
                      },
                      "en": {
                        "title": "m²"
                      },
                      "nl": {
                        "title": "m²"
                      }
                    },
                    "order": 3,
                    "scale": 1,
                    "class_name": "col-span-1"
                  },
                  "aggregate_fn": "sum"
                },
                "impact_json.rework_count": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Nacharbeit"
                      },
                      "en": {
                        "title": "Rework"
                      },
                      "nl": {
                        "title": "Herstel"
                      }
                    },
                    "order": 4,
                    "class_name": "col-span-1",
                    "hidden_when": [
                      {
                        "key": "impact_json.rework_count",
                        "op": "==",
                        "value": 0
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                },
                "impact_json.rework_amount": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "H. Einheiten"
                      },
                      "en": {
                        "title": "Rw units"
                      },
                      "nl": {
                        "title": "H. units"
                      }
                    },
                    "order": 5,
                    "class_name": "col-span-1",
                    "hidden_when": [
                      {
                        "key": "impact_json.rework_count",
                        "op": "==",
                        "value": 0
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                },
                "impact_json.rework_sqm": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "H. m²"
                      },
                      "en": {
                        "title": "Rw m²"
                      },
                      "nl": {
                        "title": "H. m²"
                      }
                    },
                    "order": 6,
                    "scale": 1,
                    "class_name": "col-span-1",
                    "hidden_when": [
                      {
                        "key": "impact_json.rework_count",
                        "op": "==",
                        "value": 0
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                }
              },
              "fields_class_name": "grid grid-cols-3 gap-1",
              "children": [
                {
                  "layout": "flow-container",
                  "children": [
                    {
                      "layout": "flow-cards",
                      "group_by": [
                        "production_orderline_id"
                      ],
                      "row_options": {
                        "nav": {
                          "menu": [
                            {
                              "i18n": {
                                "de": {
                                  "title": "Dateien"
                                },
                                "en": {
                                  "title": "Files"
                                },
                                "es": {
                                  "title": "Archivos"
                                },
                                "fr": {
                                  "title": "Fichiers"
                                },
                                "nl": {
                                  "title": "Bestanden"
                                },
                                "uk": {
                                  "title": "Файли"
                                }
                              },
                              "path": "(detail:uploader-data)",
                              "params": [
                                {
                                  "key": "production_orderline_id",
                                  "is_query_param": true
                                }
                              ]
                            },
                            {
                              "i18n": {
                                "de": {
                                  "title": "Statusverlauf"
                                },
                                "en": {
                                  "title": "Status history"
                                },
                                "es": {
                                  "title": "Historial de estados"
                                },
                                "fr": {
                                  "title": "Historique des statuts"
                                },
                                "nl": {
                                  "title": "Status verloop"
                                },
                                "uk": {
                                  "title": "Історія статусів"
                                }
                              },
                              "path": "(detail:status-log-duration)",
                              "params": [
                                {
                                  "key": "production_orderline_id",
                                  "is_query_param": true
                                }
                              ]
                            },
                            {
                              "i18n": {
                                "de": {
                                  "title": "Nest detail"
                                },
                                "en": {
                                  "title": "Nest detail"
                                },
                                "es": {
                                  "title": "Detalle del nido"
                                },
                                "fr": {
                                  "title": "Détail du nid"
                                },
                                "nl": {
                                  "title": "Nest detail"
                                },
                                "uk": {
                                  "title": "Деталі гнізда"
                                }
                              },
                              "path": "(sidebar:nest-detail)",
                              "params": [
                                {
                                  "key": "nest_ids",
                                  "is_query_param": true
                                }
                              ],
                              "hidden_when": [
                                {
                                  "key": "nest_ids[0]",
                                  "op": "==",
                                  "value": null
                                }
                              ]
                            }
                          ]
                        },
                        "colexp": false,
                        "checkable": false,
                        "selectable": true
                      },
                      "field_config": {
                        "production_orderline_id": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Auftragszeile"
                              },
                              "en": {
                                "title": "Orderline"
                              },
                              "nl": {
                                "title": "Orderregel"
                              }
                            },
                            "order": 0,
                            "hidden": false,
                            "class_name": "col-span-1"
                          }
                        },
                        "status_title": {
                          "ui": {
                            "order": 1,
                            "class_name": "col-span-2"
                          }
                        },
                        "product_amount": {
                          "ui": {
                            "order": 2,
                            "class_name": "col-span-1"
                          }
                        },
                        "sqm": {
                          "ui": {
                            "order": 3,
                            "class_name": "col-span-1"
                          }
                        },
                        "part_amount": {
                          "ui": {
                            "order": 4,
                            "class_name": "col-span-1"
                          }
                        },
                        "impact_json.rework_count": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Nacharbeit"
                              },
                              "en": {
                                "title": "Rework"
                              },
                              "nl": {
                                "title": "Herstel"
                              }
                            },
                            "order": 5,
                            "class_name": "col-span-1",
                            "hidden_when": [
                              {
                                "key": "impact_json.rework_count",
                                "op": "==",
                                "value": 0
                              }
                            ]
                          }
                        },
                        "impact_json.rework_sqm": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "H. m²"
                              },
                              "en": {
                                "title": "Rw m²"
                              },
                              "nl": {
                                "title": "H. m²"
                              }
                            },
                            "order": 6,
                            "scale": 1,
                            "class_name": "col-span-1",
                            "hidden_when": [
                              {
                                "key": "impact_json.rework_count",
                                "op": "==",
                                "value": 0
                              }
                            ]
                          }
                        },
                        "impact_json.rework_amount": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "H. Teile"
                              },
                              "en": {
                                "title": "Rw parts"
                              },
                              "nl": {
                                "title": "H. delen"
                              }
                            },
                            "order": 7,
                            "class_name": "col-span-1",
                            "hidden_when": [
                              {
                                "key": "impact_json.rework_count",
                                "op": "==",
                                "value": 0
                              }
                            ]
                          }
                        }
                      },
                      "fields_class_name": "grid grid-cols-3 gap-1"
                    }
                  ],
                  "group_by": [
                    "production_order_id",
                    "number"
                  ],
                  "row_options": {
                    "colexp": true,
                    "checkable": false,
                    "selectable": true
                  },
                  "field_config": {
                    "sqm": {
                      "ui": {
                        "order": 3,
                        "class_name": "col-span-1"
                      },
                      "aggregate_fn": "sum"
                    },
                    "number": {
                      "ui": {
                        "order": 0,
                        "class_name": "col-span-2"
                      }
                    },
                    "product_amount": {
                      "ui": {
                        "order": 2,
                        "class_name": "col-span-1"
                      },
                      "aggregate_fn": "sum"
                    },
                    "customer_json.company_name": {
                      "ui": {
                        "order": 1,
                        "class_name": "col-span-2"
                      }
                    }
                  },
                  "fields_class_name": "grid grid-cols-6 gap-1"
                }
              ]
            }
          ]
        }
      }
    ]
  },
  {
    "data_group_id": 79,
    "data_group": "nest_schedule_queue",
    "data_group_json": [
      {
        "src": [
          "get_production_orderline_manifest"
        ],
        "layout": "flow-board",
        "params": [
          {
            "key": "material_id",
            "is_query_param": true
          },
          {
            "key": "date",
            "is_optional": true,
            "is_query_param": true
          },
          {
            "key": "look_ahead_days",
            "is_optional": true,
            "default_value": -1,
            "is_query_param": true
          },
          {
            "key": "threshold",
            "is_optional": true,
            "default_value": 1,
            "is_query_param": true
          }
        ],
        "children": [],
        "widget_id": "nest_schedule_queue",
        "field_config": {
          "tenant_name": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Standort"
                },
                "en": {
                  "title": "Location"
                },
                "es": {
                  "title": "Ubicación"
                },
                "fr": {
                  "title": "Emplacement"
                },
                "nl": {
                  "title": "Locatie"
                },
                "uk": {
                  "title": "Місцезнаходження"
                }
              }
            }
          },
          "manifest_json.imposition.i18n": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Ausschießen"
                },
                "en": {
                  "title": "Imposition"
                },
                "es": {
                  "title": "Imposición"
                },
                "fr": {
                  "title": "Imposition"
                },
                "nl": {
                  "title": "Impositie"
                },
                "uk": {
                  "title": "Спуск шпальт"
                }
              },
              "control": "i18n-text"
            }
          },
          "manifest_json": {
            "ui": {
              "hidden": true
            }
          },
          "nest_date": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Datum"
                },
                "en": {
                  "title": "Date"
                },
                "es": {
                  "title": "Fecha"
                },
                "fr": {
                  "title": "Date"
                },
                "nl": {
                  "title": "Datum"
                },
                "uk": {
                  "title": "Дата"
                }
              },
              "type": "date"
            }
          },
          "queue_class_names": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Einheiten-Schwelle"
                },
                "en": {
                  "title": "Unit threshold"
                },
                "es": {
                  "title": "Umbral de unidades"
                },
                "fr": {
                  "title": "Seuil d'unités"
                },
                "nl": {
                  "title": "Units-drempel"
                },
                "uk": {
                  "title": "Поріг одиниць"
                }
              },
              "hidden": true
            }
          },
          "production_orderline_id": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Auftragsposition"
                },
                "en": {
                  "title": "Order line"
                },
                "es": {
                  "title": "Línea de pedido"
                },
                "fr": {
                  "title": "Ligne de commande"
                },
                "nl": {
                  "title": "Orderregel"
                },
                "uk": {
                  "title": "Рядок замовлення"
                }
              }
            }
          },
          "number": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Auftrag"
                },
                "en": {
                  "title": "Order"
                },
                "es": {
                  "title": "Pedido"
                },
                "fr": {
                  "title": "Commande"
                },
                "nl": {
                  "title": "Order"
                },
                "uk": {
                  "title": "Замовлення"
                }
              },
              "hidden": true
            }
          },
          "product_amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Menge"
                },
                "en": {
                  "title": "Qty"
                },
                "es": {
                  "title": "Cant."
                },
                "fr": {
                  "title": "Qté"
                },
                "nl": {
                  "title": "Aantal"
                },
                "uk": {
                  "title": "Кількість"
                }
              }
            },
            "scale": 0
          },
          "sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "m²"
                },
                "en": {
                  "title": "m²"
                },
                "es": {
                  "title": "m²"
                },
                "fr": {
                  "title": "m²"
                },
                "nl": {
                  "title": "m²"
                },
                "uk": {
                  "title": "м²"
                }
              }
            },
            "scale": 1
          },
          "product_width": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Breite"
                },
                "en": {
                  "title": "Width"
                },
                "es": {
                  "title": "Ancho"
                },
                "fr": {
                  "title": "Largeur"
                },
                "nl": {
                  "title": "Breedte"
                },
                "uk": {
                  "title": "Ширина"
                }
              }
            },
            "scale": 0
          },
          "product_height": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Höhe"
                },
                "en": {
                  "title": "Height"
                },
                "es": {
                  "title": "Alto"
                },
                "fr": {
                  "title": "Hauteur"
                },
                "nl": {
                  "title": "Hoogte"
                },
                "uk": {
                  "title": "Висота"
                }
              }
            },
            "scale": 0
          },
          "status_title": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Status"
                },
                "en": {
                  "title": "Status"
                },
                "es": {
                  "title": "Estado"
                },
                "fr": {
                  "title": "Statut"
                },
                "nl": {
                  "title": "Status"
                },
                "uk": {
                  "title": "Статус"
                }
              }
            }
          },
          "impact_json.count": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Auftragszeilen"
                },
                "en": {
                  "title": "Orderlines"
                },
                "es": {
                  "title": "Líneas de pedido"
                },
                "fr": {
                  "title": "Lignes de commande"
                },
                "nl": {
                  "title": "Orderregels"
                },
                "uk": {
                  "title": "Рядки замовлення"
                }
              }
            }
          },
          "impact_json.amount": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Einheiten"
                },
                "en": {
                  "title": "Units"
                },
                "es": {
                  "title": "Unidades"
                },
                "fr": {
                  "title": "Unités"
                },
                "nl": {
                  "title": "Units"
                },
                "uk": {
                  "title": "Одиниці"
                }
              }
            },
            "scale": 0
          },
          "impact_json.sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "m²"
                },
                "en": {
                  "title": "m²"
                },
                "es": {
                  "title": "m²"
                },
                "fr": {
                  "title": "m²"
                },
                "nl": {
                  "title": "m²"
                },
                "uk": {
                  "title": "м²"
                }
              }
            },
            "scale": 1
          },
          "impact_json.rework_count": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "Nacharbeit"
                },
                "en": {
                  "title": "Rework"
                },
                "es": {
                  "title": "Retrabajo"
                },
                "fr": {
                  "title": "Reprise"
                },
                "nl": {
                  "title": "Herstel"
                },
                "uk": {
                  "title": "Переробка"
                }
              }
            }
          },
          "impact_json.rework_sqm": {
            "ui": {
              "i18n": {
                "de": {
                  "title": "H. m²"
                },
                "en": {
                  "title": "Rw m²"
                },
                "es": {
                  "title": "Retr. m²"
                },
                "fr": {
                  "title": "Repr. m²"
                },
                "nl": {
                  "title": "H. m²"
                },
                "uk": {
                  "title": "Пер. м²"
                }
              }
            },
            "scale": 1
          },
          "class_names": {
            "ui": {
              "hidden": true
            }
          },
          "unit_class_names": {
            "ui": {
              "hidden": true
            }
          },
          "material_id": {
            "ui": {
              "hidden": true
            }
          },
          "production_company_id": {
            "ui": {
              "hidden": true
            }
          }
        },
        "flow_board_config": {
          "layout": "flow-grid",
          "group_by": [
            "tenant_name"
          ],
          "row_options": {
            "colexp": false,
            "checkable": false,
            "selectable": false
          },
          "field_config": {
            "tenant_name": {
              "ui": {
                "i18n": {
                  "de": {
                    "title": "Standort"
                  },
                  "en": {
                    "title": "Location"
                  },
                  "es": {
                    "title": "Ubicación"
                  },
                  "fr": {
                    "title": "Emplacement"
                  },
                  "nl": {
                    "title": "Locatie"
                  },
                  "uk": {
                    "title": "Місцезнаходження"
                  }
                },
                "no_label": true,
                "class_name": "col-span-1"
              }
            }
          },
          "column_min_width": 300,
          "column_max_width": 400,
          "fields_class_name": "grid grid-cols-1",
          "children": [
            {
              "layout": "flow-container",
              "group_by": [
                "manifest_json.imposition"
              ],
              "row_options": {
                "colexp": true,
                "checkable": false,
                "selectable": false
              },
              "field_config": {
                "manifest_json.imposition.i18n": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Ausschießen"
                      },
                      "en": {
                        "title": "Imposition"
                      },
                      "es": {
                        "title": "Imposición"
                      },
                      "fr": {
                        "title": "Imposition"
                      },
                      "nl": {
                        "title": "Impositie"
                      },
                      "uk": {
                        "title": "Спуск шпальт"
                      }
                    },
                    "order": 0,
                    "control": "i18n-text",
                    "no_label": true,
                    "class_name": "col-span-6 @md:col-span-2"
                  }
                },
                "impact_json.count": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Auftragszeilen"
                      },
                      "en": {
                        "title": "Orderlines"
                      },
                      "es": {
                        "title": "Líneas de pedido"
                      },
                      "fr": {
                        "title": "Lignes de commande"
                      },
                      "nl": {
                        "title": "Orderregels"
                      },
                      "uk": {
                        "title": "Рядки замовлення"
                      }
                    },
                    "order": 1,
                    "class_name": "col-span-2 @md:col-span-1 text-right"
                  },
                  "aggregate_fn": "sum"
                },
                "impact_json.amount": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Einheiten"
                      },
                      "en": {
                        "title": "Units"
                      },
                      "es": {
                        "title": "Unidades"
                      },
                      "fr": {
                        "title": "Unités"
                      },
                      "nl": {
                        "title": "Units"
                      },
                      "uk": {
                        "title": "Одиниці"
                      }
                    },
                    "order": 2,
                    "class_name": "col-span-2 @md:col-span-1 text-right"
                  },
                  "scale": 0,
                  "aggregate_fn": "sum"
                },
                "impact_json.sqm": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "m²"
                      },
                      "en": {
                        "title": "m²"
                      },
                      "es": {
                        "title": "m²"
                      },
                      "fr": {
                        "title": "m²"
                      },
                      "nl": {
                        "title": "m²"
                      },
                      "uk": {
                        "title": "м²"
                      }
                    },
                    "order": 3,
                    "class_name": "col-span-2 @md:col-span-1 text-right"
                  },
                  "scale": 1,
                  "aggregate_fn": "sum"
                },
                "impact_json.rework_count": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "Nacharbeit"
                      },
                      "en": {
                        "title": "Rework"
                      },
                      "es": {
                        "title": "Retrabajo"
                      },
                      "fr": {
                        "title": "Reprise"
                      },
                      "nl": {
                        "title": "Herstel"
                      },
                      "uk": {
                        "title": "Переробка"
                      }
                    },
                    "order": 4,
                    "class_name": "col-span-2 @md:col-span-1 text-right",
                    "hidden_when": [
                      {
                        "field": "impact_json.rework_count",
                        "op": "==",
                        "value": 0
                      }
                    ]
                  },
                  "aggregate_fn": "sum"
                },
                "impact_json.rework_sqm": {
                  "ui": {
                    "i18n": {
                      "de": {
                        "title": "H. m²"
                      },
                      "en": {
                        "title": "Rw m²"
                      },
                      "es": {
                        "title": "Retr. m²"
                      },
                      "fr": {
                        "title": "Repr. m²"
                      },
                      "nl": {
                        "title": "H. m²"
                      },
                      "uk": {
                        "title": "Пер. м²"
                      }
                    },
                    "order": 5,
                    "class_name": "col-span-2 @md:col-span-1 text-right",
                    "hidden_when": [
                      {
                        "field": "impact_json.rework_count",
                        "op": "==",
                        "value": 0
                      }
                    ]
                  },
                  "scale": 1,
                  "aggregate_fn": "sum"
                }
              },
              "fields_class_name": "@container grid grid-cols-6 gap-1",
              "children": [
                {
                  "layout": "flow-container",
                  "group_by": [
                    "nest_date",
                    "queue_class_names"
                  ],
                  "row_options": {
                    "colexp": true,
                    "checkable": false,
                    "selectable": false,
                    "class_names_field": "queue_class_names"
                  },
                  "field_config": {
                    "nest_date": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Datum"
                          },
                          "en": {
                            "title": "Date"
                          },
                          "es": {
                            "title": "Fecha"
                          },
                          "fr": {
                            "title": "Date"
                          },
                          "nl": {
                            "title": "Datum"
                          },
                          "uk": {
                            "title": "Дата"
                          }
                        },
                        "type": "date",
                        "order": 0,
                        "class_name": "col-span-6 @md:col-span-2"
                      }
                    },
                    "impact_json.count": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Auftragszeilen"
                          },
                          "en": {
                            "title": "Orderlines"
                          },
                          "es": {
                            "title": "Líneas de pedido"
                          },
                          "fr": {
                            "title": "Lignes de commande"
                          },
                          "nl": {
                            "title": "Orderregels"
                          },
                          "uk": {
                            "title": "Рядки замовлення"
                          }
                        },
                        "order": 1,
                        "class_name": "col-span-2 @md:col-span-1 text-right"
                      },
                      "aggregate_fn": "sum"
                    },
                    "impact_json.amount": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Einheiten"
                          },
                          "en": {
                            "title": "Units"
                          },
                          "es": {
                            "title": "Unidades"
                          },
                          "fr": {
                            "title": "Unités"
                          },
                          "nl": {
                            "title": "Units"
                          },
                          "uk": {
                            "title": "Одиниці"
                          }
                        },
                        "order": 2,
                        "class_name": "col-span-2 @md:col-span-1 text-right"
                      },
                      "scale": 0,
                      "aggregate_fn": "sum"
                    },
                    "impact_json.sqm": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "m²"
                          },
                          "en": {
                            "title": "m²"
                          },
                          "es": {
                            "title": "m²"
                          },
                          "fr": {
                            "title": "m²"
                          },
                          "nl": {
                            "title": "m²"
                          },
                          "uk": {
                            "title": "м²"
                          }
                        },
                        "order": 3,
                        "class_name": "col-span-2 @md:col-span-1 text-right"
                      },
                      "scale": 1,
                      "aggregate_fn": "sum"
                    },
                    "impact_json.rework_count": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "Nacharbeit"
                          },
                          "en": {
                            "title": "Rework"
                          },
                          "es": {
                            "title": "Retrabajo"
                          },
                          "fr": {
                            "title": "Reprise"
                          },
                          "nl": {
                            "title": "Herstel"
                          },
                          "uk": {
                            "title": "Переробка"
                          }
                        },
                        "order": 4,
                        "class_name": "col-span-2 @md:col-span-1 text-right",
                        "hidden_when": [
                          {
                            "field": "impact_json.rework_count",
                            "op": "==",
                            "value": 0
                          }
                        ]
                      },
                      "aggregate_fn": "sum"
                    },
                    "impact_json.rework_sqm": {
                      "ui": {
                        "i18n": {
                          "de": {
                            "title": "H. m²"
                          },
                          "en": {
                            "title": "Rw m²"
                          },
                          "es": {
                            "title": "Retr. m²"
                          },
                          "fr": {
                            "title": "Repr. m²"
                          },
                          "nl": {
                            "title": "H. m²"
                          },
                          "uk": {
                            "title": "Пер. м²"
                          }
                        },
                        "order": 5,
                        "class_name": "col-span-2 @md:col-span-1 text-right",
                        "hidden_when": [
                          {
                            "field": "impact_json.rework_count",
                            "op": "==",
                            "value": 0
                          }
                        ]
                      },
                      "scale": 1,
                      "aggregate_fn": "sum"
                    }
                  },
                  "fields_class_name": "@container grid grid-cols-6 gap-1",
                  "children": [
                    {
                      "layout": "flow-table",
                      "group_by": [
                        "production_orderline_id"
                      ],
                      "row_options": {
                        "colexp": false,
                        "checkable": true,
                        "selectable": true,
                        "class_names_field": "class_names"
                      },
                      "field_config": {
                        "production_orderline_id": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Auftragsposition"
                              },
                              "en": {
                                "title": "Order line"
                              },
                              "es": {
                                "title": "Línea de pedido"
                              },
                              "fr": {
                                "title": "Ligne de commande"
                              },
                              "nl": {
                                "title": "Orderregel"
                              },
                              "uk": {
                                "title": "Рядок замовлення"
                              }
                            },
                            "order": 0,
                            "class_name": "col-span-2"
                          }
                        },
                        "product_amount": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Menge"
                              },
                              "en": {
                                "title": "Qty"
                              },
                              "es": {
                                "title": "Cant."
                              },
                              "fr": {
                                "title": "Qté"
                              },
                              "nl": {
                                "title": "Aantal"
                              },
                              "uk": {
                                "title": "Кількість"
                              }
                            },
                            "order": 1,
                            "class_name": "col-span-1 text-right"
                          },
                          "scale": 0
                        },
                        "sqm": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "m²"
                              },
                              "en": {
                                "title": "m²"
                              },
                              "es": {
                                "title": "m²"
                              },
                              "fr": {
                                "title": "m²"
                              },
                              "nl": {
                                "title": "m²"
                              },
                              "uk": {
                                "title": "м²"
                              }
                            },
                            "order": 2,
                            "class_name": "col-span-1 text-right"
                          },
                          "scale": 1
                        },
                        "product_width": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Breite"
                              },
                              "en": {
                                "title": "Width"
                              },
                              "es": {
                                "title": "Ancho"
                              },
                              "fr": {
                                "title": "Largeur"
                              },
                              "nl": {
                                "title": "Breedte"
                              },
                              "uk": {
                                "title": "Ширина"
                              }
                            },
                            "order": 3,
                            "class_name": "col-span-1 text-right"
                          },
                          "scale": 0
                        },
                        "product_height": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Höhe"
                              },
                              "en": {
                                "title": "Height"
                              },
                              "es": {
                                "title": "Alto"
                              },
                              "fr": {
                                "title": "Hauteur"
                              },
                              "nl": {
                                "title": "Hoogte"
                              },
                              "uk": {
                                "title": "Висота"
                              }
                            },
                            "order": 4,
                            "class_name": "col-span-1 text-right"
                          },
                          "scale": 0
                        },
                        "impact_json.rework_count": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Nacharbeit"
                              },
                              "en": {
                                "title": "Rework"
                              },
                              "es": {
                                "title": "Retrabajo"
                              },
                              "fr": {
                                "title": "Reprise"
                              },
                              "nl": {
                                "title": "Herstel"
                              },
                              "uk": {
                                "title": "Переробка"
                              }
                            },
                            "order": 5,
                            "class_name": "col-span-1 text-right",
                            "hidden_when": [
                              {
                                "field": "impact_json.rework_count",
                                "op": "==",
                                "value": 0
                              }
                            ]
                          }
                        },
                        "status_title": {
                          "ui": {
                            "i18n": {
                              "de": {
                                "title": "Status"
                              },
                              "en": {
                                "title": "Status"
                              },
                              "es": {
                                "title": "Estado"
                              },
                              "fr": {
                                "title": "Statut"
                              },
                              "nl": {
                                "title": "Status"
                              },
                              "uk": {
                                "title": "Статус"
                              }
                            },
                            "order": 6,
                            "class_name": "col-span-1"
                          }
                        }
                      },
                      "fields_class_name": "grid grid-cols-8 gap-1"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    ]
  }
]$dg$::jsonb AS doc
),
src AS (
    SELECT (el ->> 'data_group_id')::integer AS data_group_id,
           el ->> 'data_group'               AS data_group,
           el -> 'data_group_json'           AS data_group_json
    FROM payload
             CROSS JOIN LATERAL jsonb_array_elements(payload.doc) AS el
),
updated AS (
    UPDATE site.data_group t
    SET data_group      = s.data_group,
        data_group_json = s.data_group_json
    FROM src s
    WHERE t.data_group_id = s.data_group_id
      AND (t.data_group_json IS DISTINCT FROM s.data_group_json
           OR t.data_group IS DISTINCT FROM s.data_group)
    RETURNING t.data_group_id
)
INSERT INTO site.data_group (data_group_id, data_group, data_group_json)
OVERRIDING SYSTEM VALUE
SELECT s.data_group_id, s.data_group, s.data_group_json
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM site.data_group t WHERE t.data_group_id = s.data_group_id);

-- data_group_id is an identity column; after inserting explicit ids the
-- sequence has to catch up, or the next generated id collides
SELECT setval(pg_get_serial_sequence('site.data_group', 'data_group_id'),
              (SELECT max(data_group_id) FROM site.data_group));

COMMIT;
